package fr.gymgod.etl.domain.model;

import fr.gymgod.common.entities.nutrition.Country;

import java.util.*;
import java.util.stream.Collectors;

public class DataCountry {

    public static final List<Country> COUNTRY_DEFINITIONS = new ArrayList<>();

    static {
        String[][] rawMappings = {
                { "afghanistan", "af", "افغانستان", "ประเทศรัสเซีย" },
                { "afrique du sud", "south africa", "südafrika", "suid-afrika", "republika południowej afryki",
                        "zuid-afrika", "южна африка", "جنوب أفريقيا", "南アフリカ共和国", "za", "sudafrica", "sudáfrica",
                        "νότια αφρική", "áfrica do sul", "south-africa", "sydafrika" },
                { "albanie", "albania", "albanien", "albanija", "albanië", "albánie", "albânia", "shqipëria", "албания",
                        "албанија", "アルバニア", "македонија", "andore", "al" },
                { "algérie", "algeria", "algerie", "algerien", "algeriet", "algerije", "algieria", "algéria", "almanya",
                        "argelia", "argélia", "الجزائر", "アルジェリア", "dz", "алжир", "fr:algérie", "alžir" },
                { "allemagne", "germany", "deutschland", "de", "alemanha", "alemania", "alemanya", "almanya",
                        "germania", "nemecko", "nemčija", "niemcy", "njemačka", "saksa", "tyskland", "vokietija",
                        "германия", "немачка", "німеччина", "ألمانيا", "ドイツ", "中国", "a' ghearmailt", "duitsland",
                        "německo", "de:deutschland", "de:germany", "pl:niemcy", "γερμανία", "독일", "ประเทศเยอรมนี",
                        "de:allemagne", "németország", "fr:allemagne", "fr:deutschland", "baden-württemberg",
                        "98646 straufhain", "[{&quot;value&quot;:&quot;germany&quot;}]", "de:de:deutschland",
                        "it:germania", "de:německo", "גרמניה", "german" },
                { "allemagne de l'est (rda)", "deutsche demokratische republik", "east germany",
                        "république démocratique allemande" },
                { "andorre", "andora", "andorra", "andore", "андорра", "ad" },
                { "angola", "ao" },
                { "anguilla", "ai" },
                { "antigua-et-barbuda", "antigua and barbuda", "ag" },
                { "arabie saoudite", "saudi arabia", "arab saudi", "arabia saudita", "arabia saudită",
                        "arabia saudyjska", "arábia saudita", "saudi-arabien", "saudiarabien", "saudijska arabija",
                        "السعودية", "ערב السعوديת", "サウジアラビア", "沙特阿拉伯", "ประเทศซาอุดีอาระเบีย", "saudi-arabia",
                        "ar:saudi arabia", "saoedi-arabië", "ערב הסعودية" },
                { "argentine", "argentina", "es:en:argentina", "argentinien", "argentyna", "الأرجنتين", "es:argentina",
                        "аржентина", "аргентина", "ar", "fr:en:ar", "es:ar", "fr:ar" },
                { "arménie", "armenia", "armenien", "armenië", "հայաստան", "армения", "am", "az" },
                { "aruba", "aw" },
                { "australie", "ประเทศออสเตรเลีย", "australia", "australien", "australija", "australië", "austrália",
                        "austrálie", "ausztrália", "австралия", "австралійський союз", "אוסטרליה", "オーストラリア", "澳大利亚",
                        "au", "aus", "ประเทศออสเตรีย", "fr:australie" },
                { "autriche", "austria", "austrija", "austrália", "austrálie", "ausztria", "ausztrália", "avstrija",
                        "avusturya", "itävalta", "rakousko", "rakúsko", "österreich", "österrike", "østerrike",
                        "østrig", "αυστρία", "австрия", "австрія", "奥地利", "at", "de:autriche", "oostenrijk",
                        "it:austria", "fr:autriche", "ประเทศออสเตรีย", "áustria", "ôsterreich", "de:österreich" },
                { "azerbaïdjan", "azerbaijan", "azərbaycan", "aserbaidschan", "азербайджан", "ru:азербайджан", "az" },
                { "bahamas", "the bahamas", "ba", "bs" },
                { "bahreïn", "bahrain", "bahrein", "البحرين", "bh" },
                { "bangladesh", "bangladesch", "bangladés", "বাংলাদেশ", "bd" },
                { "barbade", "barbados", "bb" },
                { "belgique", "belgium", "belgië", "belgien", "belgia", "belgicko", "belgie", "belgija", "nl:be",
                        "nl:en:be", "belgio", "beļģija", "bèlgica", "bélgica", "βέλγιο", "белгия", "белгија", "бельгия",
                        "бельгія", "بلجيكا", "ベルギー", "比利时", "be", "nl:belgië", "de:belgium", "ბელგია", "ประเทศเบลเยียม",
                        "fr:belgica", "fr:belgium", "fr:belgique", "fr:fr", "fr:be", "belçika", "fr:bélgica",
                        "nl:belgie", "be." },
                { "belize", "belice", "bz" },
                { "bénin", "benim", "benin", "bj" },
                { "bermudes", "bermuda", "bm" },
                { "biélorussie", "belarus", "wit-rusland", "by", "weissrussland", "белоруссия", "беларусь", "bělorusko",
                        "ru:belarus", "białoruś", "bielorussia" },
                { "bhoutan", "bhoutan", "bhutan", "ভুটান" },
                { "bolivie", "bolivia", "bolivien", "bolívia", "bo" },
                { "bosnie-herzégovine", "bosnia and herzegovina", "bosna i hercegovina", "босна и херцеговина",
                        "bosnien und herzegowina", "bosnië en herzegovina", "bih", "bosna a hercegovina",
                        "bośnia i hercegowina", "république serbe de bosnie", "bosnia", "bosna in hercegovina",
                        "bosnia y herzegovina", "bosnia ed erzegovina", "república srpska" },
                { "botswana", "bw" },
                { "brésil", "brazil", "brasil", "brasile", "brasilien", "brazylia", "br", "brazil  france",
                        "brésil:orange", "martinik" },
                { "brunéi", "brunei", "bn" },
                { "bulgarie", "bulgaria", "bulgarien", "bulgarija", "bulgarije", "bulgaristan", "bulgária", "bulharsko",
                        "bułgaria", "bugarska", "βουλγαρία", "българия", "ブルガリア", "保加利亚", "bg", "bg:българия",
                        "fr:българия", "bg:bulgaria", "bg::bulgaria", "болгария", "болгарія" },
                { "burkina faso", "fr:burkina faso", "bf" },
                { "burundi", "bi" },
                { "cambodge", "ព្រះរាជាណាចក្រកម្ពុជា", "cambodia", "cambogia", "camboya", "ประเทศกัมพูชา", "kh" },
                { "cameroun", "cameroon", "camerun", "camerún", "камерун", "الكاميرون", "cm", "kamerun" },
                { "canada", "ประเทศแคนาดา", "canada", "canadà", "canadá", "kanada", "канада", "كندا", "カナダ", "加拿大",
                        "ca", "bg:canada", "fr:canada", "canada (ca)", "bc canada", "western canada", "캐나다", "québec",
                        "conagra brands mississauga on canada l4w 5k7",
                        "made in canada with domestic and imported material", "british columbia canada",
                        "vancouver bc canada", "fr:ca", "fr:quebec", "abbotsford bc", "surrey bc canada" },
                { "cap-vert", "cabo verde", "cape verde", "cv" },
                { "catalunya", "ca:catalunya" },
                { "chili", "chile", "cile", "čile", "чили", "cl", "it:cile", "es:chile" },
                { "chine", "china", "cina", "chińska republika ludowa", "китайская narodna republika", "中华人民共和国", "中国",
                        "cn", "香港", "volksrepubliek china", "it:cina", "republica populară chineză", "中華人民共和国",
                        "китайская народная республика" },
                { "chypre", "cyprus", "chipre", "cipar", "cipro", "cypr", "κύπρος", "кипар", "кипър", "cy",
                        "republik zypern", "kibris cumhuriyeti", "tr:kibris cumhuriyeti", "республика кипр" },
                { "colombie", "colombia", "colômbia", "kolumbia", "kolumbien", "co", "es:colombia", "es:co",
                        "es:en:colombia" },
                { "comores", "comoros", "km" },
                { "congo", "republic of the congo", "république du congo", "republic-of-the-congo",
                        "república del congo", "republik kongo", "cg", "congo republic" },
                { "corée du nord", "north korea", "kp" },
                { "corée du sud", "south korea", "corea del sud", "corea del sur", "coreia do sul", "dél-korea",
                        "južna koreja", "korea południowa", "korea selatan", "korean tasavalta", "südkorea",
                        "zuid-korea", "республика корея", "ประเทศเกาหลีใต้", "대한민국", "kr", "de:südkorea", "south-korea",
                        "fr:corée du sud" },
                { "costa rica", "cr", "costa-rica", "es:costa rica" },
                { "côte d’ivoire", "côte d'ivoire", "costa d'avorio", "costa de marfil", "elfenbeinküste", "ivoorkust",
                        "obala bjelokosti", "кот д'ивоар", "كوت ديفوار", "ci", "ivory coast", "ακτή ελεφανโตสτού",
                        "ประเทศโกตดิวัวร์", "cote-d-ivoire" },
                { "croatie", "croatia", "croacia", "croazia", "croația", "croácia", "chorvatsko", "chorvátsko",
                        "chorwacja", "horvátország", "hrvatska", "hrvaška", "kroatia", "kroatien", "kroatija",
                        "kroatië", "κροατία", "хорватия", "хорватія", "хърватия", "hr", "hr:hrvatska" },
                { "cuba", "kuba", "cu" },
                { "curaçao", "curazao", "cw", "curacao" },
                { "danemark", "denmark", "dania", "danimarca", "danmark", "danska", "denemarken", "dánmárku", "dánsko",
                        "dänemark", "tanska", "tjekkiet", "δανία", "дания", "デンマーク", "丹麦", "dk", "dinamarca",
                        "ประเทศเดนมาร์ก" },
                { "djibouti", "dj" },
                { "dominique", "dominica", "dm" },
                { "égypte", "egypt", "egipt", "egipto", "egito", "egitto", "ägypten", "مصر", "eg", "usa egypt" },
                { "émirats arabes unis", "united arab emirates", "uae", "emirados árabes unidos", "emirati arabi uniti",
                        "emiratos árabes unidos", "yhdistyneet arabiemiirikunnat", "обединени арабски емирства",
                        "объединённые арабские эмираты", "الإمارات العربية المتحدة", "アラブ首長国連邦", "ae",
                        "verenigde arabische emiraten", "united-arab-emirates", "fr:émirats arabes unis",
                        "عربي متحده امارات", "vereinigte arabische emirate", "emirats-arabes-unis",
                        "zjednoczone emiraty arabaty", "dubai", "zjednoczone emiraty arabskie" },
                { "équateur", "ecuador", "ec" },
                { "érythrée", "er" },
                { "éthiopie", "ethiopia", "etiopija", "etiopía", "et" },
                { "espagne", "francia  españa", "es:en:spain", "spain", "españa", "espainia", "espanha", "espanja",
                        "espanya", "hiszpania", "ispanija", "spagna", "spania", "spanien", "spanje", "spanyolország",
                        "španjolska", "španělsko", "i̇spanya", "ισπανία", "испания", "шпанија", "ספרד", "スペイン", "西班牙",
                        "es", "es:spain", "es:españa", "es:es:españa", "španielska", "іспанія", "ესპანეთი",
                        "ประเทศสเปน", "pt:españa", "france  spain", "it:spagna", "francia  espagne", "es:francia",
                        "ca:franca", "es:cantabria", "illa de la reunió", "santoña", "cantabria", "asturias",
                        "es:santoña", "fr:espagne", "es:santona", "es:es:spain", "spánia", "espana", "mallorca",
                        " españa" },
                { "estonie", "estonia", "eesti", "estland", "estonija", "estonsko", "estónia", "viro", "эстония",
                        "爱沙尼亚", "ee", "естонія", "естония", "et:eesti", "ru:эстония", "lt:estija" },
                { "états-unis", "stati uniti d'america", "united-states", "verenigde staten van amerika",
                        "vereinigte staaten von amerika", "united states", "us", "es:américa", "américa", "usa",
                        "america", "eeuu", "estados unidos", "stany zjednoczone", "yhdysvallat",
                        "ηνωμένες πολιτείες αμερική", "соединённые штаты америки", "ארצות הברית", "الولايات المتحدة",
                        "アメリカ合衆国", "美国", "u.s.a", "united-states-of-america", "fr:us", "fr:en:us", "สหรัฐอเมริกา",
                        "spojené státy americké", "états-unis d'amérique", "etats-unis", "estados-unidos",
                        "sjedinjene americke države", "états unis", "hoa kỳ", "na stàitean aonaichte",
                        "jungtinės amerikos valstijos", "as:united states", "united states of america", "état unis",
                        "съединени американски щати", "u.s.a.", "wa usa", "sjedinjene američke države", "bg:сащ",
                        "ایالات متحده آمریکا", "संयुक्त राज्य अमेरिका", "মার্কিন যুক্তরাষ্ট্র", "amerika syarikat",
                        "ameriketako estatu batuak", "amerikai egyesült államok", "statele unite ale americii",
                        "сполучені штати америки", "ηνωμένες πολιτείες αμερικής",
                        "amerika birleşik développement de l'amérique" },
                { "fidji", "fiji", "fj" },
                { "finlande", "finland", "finlandia", "finlândia", "finnland", "finska", "finsko", "puola", "suomi",
                        "suopma", "финландия", "フィンランド", "fi", "fi:suomi", "פינלנד", "ประเทศฟินแลนด์", "venäjä",
                        "[{&quot;value&quot;:&quot;finland&quot;}]" },
                { "france", "ประเทศฝรั่งเศs", "fr", "fr:en:france", "fr:en:fr", "fr:fr:en:fr", "an fhraing", "franca",
                        "francia", "franciaország", "francie", "francija", "francja", "francuska", "francúzsko",
                        "frankreich", "frankrig", "frankriika", "frankrijk", "frankrike", "fransa", "frantsa",
                        "frantzia", "frança", "franța", "prancūzija", "prantsusmaa", "γαλλία", "франция", "францыя",
                        "франція", "צרפת", "فرنسا", "フランス", "法国", "ranska", "ประเทศฝรั่งเศส", "fr:fr:france",
                        "fr:france", "fr:francia", "ספרד", "საფრანგეთი", "फ़्रान्स", "pháp", "프랑스", "angleterre",
                        "fr:fr:fr", "perancis", "француска", "it:france", "fr:франция", "fr:frankreich", "fr:fr",
                        "ફ્રાન્સ", "france.", "ca:frança", "de:frankreich", "francese", "de:fr", "it:fr", "فرانسه",
                        "fr\u00a0 \u20ac", "dom tom", "fr:dom-tom", "fr:dom tom" },
                { "gabon", "gabun", "gabón", "ga" },
                { "gambie", "gambia", "gm" },
                { "géorgie", "georgia", "georgien", "gruzija", "gruzja", "საქართველო", "грузия", "грузія", "ge",
                        "ru:грузия", "gi" },
                { "ghana", "gh", "γκάνα", "غانا" },
                { "gibraltar", "gi" },
                { "grenade", "grenada", "granada", "gd" },
                { "groenland", "greenland" },
                { "grèce", "greece", "graikija", "grecia", "grecja", "grekland", "griechenland", "griekenland",
                        "grécia", "grčka", "hellas", "řecko", "ελλάδα", "ελλάς", "греция", "гърция", "gr", "it:grecia",
                        "fr:grèce", "görögország", "γουαдеλούπη", "ελλας", "ελλαδα" },
                { "guadeloupe", "γουαдеλούπη", "gwadelupa", "guadalupe", "гваделупа", "gp" },
                { "guatemala", "gt", "fr:gt" },
                { "guernesey", "guernsey", "je", "gg" },
                { "guinée", "guinea", "gn" },
                { "guinée-bissau", "غينيا بيساو", "guinea-bissau" },
                { "guinée équatoriale", "equatorial guinea", "guinea ecuatorial", "gq" },
                { "guyane française", "french guiana", "französisch-guayana", "guayana francesa", "guiana francesa",
                        "guyane", "gf" },
                { "guyana", "gy" },
                { "guam", "グアム", "gu" },
                { "haïti", "haiti", "haití", "ht" },
                { "honduras", "hn" },
                { "hong kong", "hongkong", "hk", "hong-kong", "хонконг", "เขตบริหารพิเศษฮ่องกง" },
                { "hongrie", "hungary", "hongarije", "hungria", "hungría", "madžarska", "magyarország", "maďarsko",
                        "mađarska", "węgry", "венгрия", "унгария", "ハンガリー", "匈牙利", "hu", "hu:magyarország", "ungarn",
                        "ungheria", "мађарска", "ประเทศฮังการี", "unkari", "ungaria", "угорщина", "ro:ungaria" },
                { "îles caïmans", "cayman islands", "ky" },
                { "île de man", "mannin", "isle of man", "isla de man", "im" },
                { "îles cook", "cook islands", "ck" },
                { "îles féroé", "frakland", "färöer", "færøerne", "faroe islands", "wyspy owcze", "fo" },
                { "îles marshall", "mh", "marshall islands" },
                { "îles mariannes du nord", "northern mariana islands", "mp" },
                { "îles salomon", "sb", "solomon islands" },
                { "îles turques-et-caïques", "turks and caicos islands", "tc" },
                { "îles vierges britanniques", "vg", "british virgin islands" },
                { "îles vierges des états-unis", "virgin islands of the united states",
                        "หมู่เกาะเวอร์จินของสหรัฐอเมริกา", "quần đảo virgin thuộc mỹ", "vi", "u.s. virgin islands" },
                { "inde", "india", "indie", "indien", "índia", "индия", "भारत", "インド", "in", "ประเทศอินเดีย",
                        "indian subcontinent" },
                { "indonésie", "indonesia", "indonesien", "indonesië", "indonezja", "印度尼西亚", "id", "indonesie",
                        "ประเทศอินโดนีเซีย" },
                { "irak", "iraq", "iraque", "العراق", "イラク", "iq", "ประเทศอิรัก", "kurdistan irakien",
                        "iraqi kurdistan" },
                { "iran", "ایران", "ir", "írán", "irán" },
                { "irlande", "ireland", "airija", "ierland", "iirimaa", "irland", "irlanda", "irlandia", "irlanti",
                        "irska", "irsko", "írország", "īrija", "poblachd na h-èireann", "ірландія", "ie",
                        "poblacht na héireann", "república da irlanda", "アイルランド", "република ирландия", "ireland & uk",
                        "iteland", "de:ireland" },
                { "islande", "iceland", "ijsland", "island", "islanda", "islandia", "islanti", "islândia", "is",
                        "ísland" },
                { "israël", "israel", "izrael", "ישראל", "il", "he:ישראל", "израел", "израиль" },
                { "italie", "italy", "italia", "italien", "italija", "italië", "itàlia", "itália", "itálie", "włochy",
                        "ιταλία", "италия", "італія", "איטליה", "إيطاليا", "イタリア", "意大利", "it", "it:it", "it:italia",
                        "it:italy", "it:it:italy", "de:italien", "ประเทศอิตาลี", "olaszország", "fr:italie",
                        "fr:italien", "es:italia", "adrano" },
                { "jamaïque", "jamaica", "jamaika", "jm" },
                { "japon", "japan", "giappone", "japani", "japonia", "japonija", "japonsko", "japão", "japón", "japāna",
                        "япония", "日本", "jp", "fr:japon", "ประเทศญี่ปุ่น", "японія", "milk from japan", "choshi",
                        "chiba" },
                { "jersey", "je" },
                { "jordanie", "jordan", "jordania", "jordanien", "jordanië", "jordánsko", "jordânia", "giordania",
                        "الاردن", "jo", "йордания", "الأردن", "jorsan", "hashemite kingdom of jordan" },
                { "kazakhstan", "kasachstan", "kazahstan", "казахстан", "kz", "ru:казахстан", "kazachstan" },
                { "kenya", "kenia", "ke", "ken" },
                { "kirghizistan", "kyrgyzstan", "kirgisistan", "ru:киргизия", "киргизия" },
                { "kosovo", "xk" },
                { "koweït", "kuwait", "koeweit", "kuwejt", "الكويت", "kw", "кувейт" },
                { "laos", "ประเทศลาว", "la" },
                { "lesotho" },
                { "lettonie", "latvia", "latvija", "letland", "letonia", "lettland", "letónia", "lotyšsko", "läti",
                        "латвия", "латвія", "lv", "łotwa", "ประเทศลัตเวีย", "lt:latvija", "拉脫維亞" },
                { "liban", "lebanon", "libano", "libanon", "líbano", "لبنان", "lb", "ливан", "fr:liban" },
                { "libéria", "liberia", "lr" },
                { "libye", "libya", "libia", "libyen", "líbia", "ليبيا", "ly", "лівія", "либия", "fr:ly", "fr:en:ly" },
                { "liechtenstein", "lihtenštajn", "li" },
                { "lituanie", "lithuania", "liettua", "lietuva", "litauen", "litouwen", "lituania", "lituânia", "litva",
                        "litvánia", "litwa", "литва", "lt", "lt:lietuva", "ru:литва", "ليتوانيا", "立陶宛", "čekija",
                        "republic of lithuania" },
                { "luxembourg", "luxemburg", "luxemburgo", "luxenburgo", "lussemburgo", "lucembursko", "luksemburg",
                        "lëtzebuerg", "люксембург", "ルクセンブルク", "lu", "de:luxemburg", "fr:luxembourg",
                        "lëtzebuerg (land)", "ประเทศลักเซมเบิร์ก", "fr:lux", "fr:lu" },
                { "macao", "macau", "澳门", "mo" },
                { "macédoine du nord", "north macedonia", "macedonia del nord", "severní makedonie",
                        "северна македония", "mk", "nordmazedonien", "sjeverna makedonija", "македонија",
                        "république de macédoine", "republic-of-macedonia", "macedonia del norte",
                        "fr:macédoine du nord", "republic of macedonia", "република македонија",
                        "république de macéédoine", "macedonia", "macedonia północna", "северная македония" },
                { "madagascar", "madagaskar", "mg", "マダガスカル", "madagascar - toamasina" },
                { "malaisie", "malaysia", "malasia", "maleisië", "malesia", "malezja", "malásia", "my",
                        "ประเทศมาเลเซีย", "马来西亚" },
                { "malawi", "mw" },
                { "maldives", "maldive", "malediwy", "mv" },
                { "mali", "ml" },
                { "malte", "malta", "малта", "mt" },
                { "maroc", "morocco", "marocco", "marocko", "marokko", "marokkó", "maroko", "marrocos", "marruecos",
                        "المغرب", "モルコ", "摩洛哥", "ma", "fr:morocco", "ar:المغرب 🇲🇦", "𝚖𝚊𝚛𝚘𝚌", "марокко", "мароко",
                        "fr:maroc", "ประเทศโมร็อกโก", "fas", "モロッコ" },
                { "maurice", "mauritius", "mauricijus", "mauricio", "mu", "ประเทศมอริเชียส", "île maurice", "毛里求斯" },
                { "mauritanie", "mauritania", "mr" },
                { "mayotte", "yt" },
                { "mexique", "mexico", "meksiko", "meksyk", "messico", "mexiko", "méxico", "μεξικό", "мексико", "メキシコ",
                        "墨西哥", "mx", "es:méxico", "republica mexicana", "ประเทศเม็กซิโก", "es:mexico", "fr:mexique",
                        "fr:mx" },
                { "moldavie", "moldova", "moldavia", "moldavië", "moldávia", "mołdawia", "молдова", "md", "moldawien",
                        "republica moldova", "молдавия", "moldavsko", "nl:moldavie", "republic of moldova" },
                { "monaco", "monako", "mónaco", "mc", "principato di monaco" },
                { "mongolie", "mongolia", "mongolei", "монголия", "mn", "монгол улс" },
                { "montserrat", "ms" },
                { "monténégro", "montenegro", "crna gora", "me", "črna gora", "černá hora", "црна гора" },
                { "mozambique", "moçambique", "mz" },
                { "myanmar", "birmanie", "birmania", "mm", "ประเทศพม่า" },
                { "namibie", "namibia", "na" },
                { "népal", "nepal", "np", "เนปาล", "नेपाल", "ประเทศเนปาล", "নেপাল" },
                { "nicaragua", "nicarágua", "ni" },
                { "niger", "nijer", "ne" },
                { "nigeria", "ng" },
                { "norvège", "norway", "norge", "norja", "norsko", "noruega", "norvegia", "norveška", "νορβηγία",
                        "норвегия", "ノルウェー", "no", "norwegen", "noorwegen", "norga", "ประเทศนอร์เวย์", "fr:no",
                        "norwegia" },
                { "nouvelle-calédonie", "new caledonia", "neukaledonien", "nieuw-caledonië", "fr:nouvelle-calédonie",
                        "nya kaledonien", "nueva caledonia", "nowa kaledonia", "new-caledonia", "nuova caledonia",
                        "нова каледония", "ニューカレドニア", "นิวแคลิโดเนีย", "nouvelle caledonie", "nc" },
                { "nouvelle-zélande", "new zealand", "aotearoa", "neuseeland", "nieuw-zeeland", "nova zelândia",
                        "novi zeland", "nový zéland", "nowa zelandia", "nueva zelanda", "nuova zelanda", "ニュージーランド",
                        "nz", "ประเทศนิวซีแลนด์", "selandia baru", "nya zeeland", "new-zealand", "новая зеландия",
                        "nouvelle zélande", "nederländerna", "ניו זילนด์" },
                { "oman", "omán", "سلطنة عمان", "om" },
                { "ouganda", "uganda", "ug" },
                { "ouzbékistan", "uzbekistan", "usbekistan", "узбекистан", "uz", "ru:узбекиستان" },
                { "pakistan", "pakistán", "paquistão", "پاکستان", "パキスタン", "pk" },
                { "palaos", "pw", "palau" },
                { "panama", "panamá", "pa" },
                { "papouasie-nouvelle-guinée", "papua new guinea", "pg" },
                { "paraguay", "paraguai", "es:paraguay", "py" },
                { "pays-bas", "netherlands", "nederland", "alankomaat", "belanda", "holandia", "holland", "hollande",
                        "niederlande", "nyderlandai", "olanda", "paesi bassi", "países baixos", "países bajos",
                        "нидерланды", "هولندا", "オランダ", "荷蘭", "nl", "fr:nederland", "fr:pays-bas", "nederlân",
                        "nederländerna", "нідерланди", "nizozemska", "nizozemsko", "เนเเดอร์แลนด์", "нидерландия",
                        "fr:netherlands", "nl:nederland", "네덜란드", "fr:frankrijk", "the netherlands" },
                { "pays-bas caribéens", "sint maarten", "sint-maarten", "caribbean netherlands", "bonaire",
                        "sint eustatius", "caribisch nederland", "and saba", "bq" },
                { "palestine", "territoires palestiniens", "palestinian territories", "فلسطين", "état de palestine",
                        "territorios palestinos", "state of palestine", "الأراضي الفلسطينية", "stato di palestina",
                        "territori palestinesi", "ps" },
                { "pérou", "peru", "perú", "pe", "es:perú" },
                { "philippines", "filipijnen", "filipina", "filipinas", "filipiny", "filippinene", "フィリピン", "ph",
                        "ประเทศフィリピン", "philippinen", "ประเทศฟิลิปปินส์" },
                { "pologne", "poland", "lengyelország", "lenkija", "polska", "polsko", "polónia", "poľsko", "puola",
                        "полша", "польша", "波兰", "pl", "poljska", "polen", "pl:polska", "it:polonia", "pl:poland",
                        "польща", "ru:польша", "ประเทศโปแลนด์", "polonia", "lt:lenkija" },
                { "polynésie française", "french polynesia", "frans-polynesië", "französisch-polynesien",
                        "polinesia francesa", "polinésia francesa", "pf", "polynésie francaise", "เฟรนช์โปลินีเซีย",
                        "polinesia francese", "polinesia perancis" },
                { "porto rico", "puerto rico", "puerto-rico", "pr" },
                { "portugal", "portogallo", "portugalia", "portugalsko", "portugália", "البرتغال", "葡萄牙", "pt",
                        "португалия", "fr:portugal", "pt:portugal", "pt:pt" },
                { "qatar", "qa", "قطر", "katar" },
                { "république centrafricaine", "zentralafrikanische republik", "central african republic", "cf" },
                { "république démocratique du congo", "democratic republic of the congo", "dr congo", "cd",
                        "kongo-kinshasa", "demokratická republika kongo", "république democratique du congo",
                        "república democrática del congo" },
                { "république dominicaine", "dominican republic", "república dominicana", "do", "es:dominican republic",
                        "repubblica dominicana", "dominican-republic" },
                { "république tchèque", "czech republic", "czechia", "tchéquie", "cehia", "csehország", "czechy",
                        "tjeckien", "tjekkiet", "tschechien", "tsjechië", "txekia", "tšekki", "чехия", "捷克", "cz",
                        "česko", "češka", "república checa", "de:république tchèque", "чехія", "česká republika",
                        "สาธารณรัฐเช็ก", "rusko", "repubblica ceca", "eslovaquia", "cs:česko", "moldavsko",
                        "sk:německo", "slovacia" },
                { "réunion", "la-reunion", "reunion", "riunione", "reunião", "reunión", "re", "la réunion",
                        "fr:la réunion", "реюнион", "france - la réunion", "illa de la reunió", "レユニオン" },
                { "roumanie", "romania", "roemenie", "roemenië", "romanus", "románia", "românia", "roménia", "rumania",
                        "rumunia", "rumunija", "rumunjska", "rumunsko", "rumänien", "румъния", "румыния", "رومانيا",
                        "ro", "it:romania", "nl:roemenie", "ro:romania", "румунія", "ประเทศโรมาเนีย", "羅馬尼亞", "rometta",
                        "fr:ro" },
                { "royaume-uni", "en", "united kingdom", "uk", "royaume - uni", "an rìoghachd aonaichte",
                        "birleşik krallik", "england", "great britain", "jungtinė karalystė", "reeriaght unnaneysit",
                        "regno unito", "reino unido", "spojené království", "spojené kráľovstvo", "storbritannia",
                        "storbritannien", "wielka brytania", "ηνωμένο βασίλειο", "великобритания", "المملكة المتحدة",
                        "イギリス", "英国", "gb", "vereinigtes königreich", "united-kingdom", "nagy-britannia",
                        "verenigd koninkrijk", "yhdistynyt kingdom", "สหราชอาณาจักร", "ujedinjeno kraljevstvo",
                        "it:regno unito", "it:uk", "tr:birleşik krallik",
                        "обединено кралство великобритания и северна ирландия", "велика британія",
                        "zjednoczone królestwo", "y deyrnas unedig",
                        "regatul unit al marii britanii și al irlandei de nord", "angleterre", "fr:angleterre",
                        "fr:angle", "angle", "wales", "nl:verenigd koninkrijk", "de:vereinigtes königreich",
                        "vereinigtes königreich grossbritannien und nordirland", "გაერთიანებული სამეფო", "mn:gb",
                        "royaume uni", "scotland", "yhdistynyt kuningaskunta", "युक्तराज्य" },
                { "russie", "russia", "nga", "rosja", "rússia", "ryssland", "россия", "росія", "русия", "俄罗斯", "ru",
                        "rusland", "russland", "rusia", "русија", "ru:russia", "rus", "ประเทศรัสเซีย",
                        "russian federation", "rusija", "oroszország" },
                { "rwanda", "ruanda", "rw" },
                { "saint-barthélemy", "saint barthélemy" },
                { "saint-christophe-et-niévès", "saint kitts and nevis", "kn", "st kitts and nevis" },
                { "sainte-hélène", "saint-helena" },
                { "sainte-lucie", "saint lucia", "santa lucía", "lc" },
                { "saint-marin", "san marino", "sm" },
                { "saint-martin", "saint martin", "sint maarten", "san martín", "mf" },
                { "saint-pierre-et-miquelon", "saint pierre and miquelon", "saint-pierre und miquelon", "pm" },
                { "saint-vincent-et-les-grenadines", "san vicente y las granadinas", "saint vincent and the grenadines",
                        "vc", "st vincent and grenadines", "saint-vincent-and-the-grenadines" },
                { "salvador", "el salvador", "salwador", "el-salvador" },
                { "samoa" },
                { "samoa américaines", "american samoa", "as" },
                { "sao tomé-et-principe", "sao tomé and príncipe", "st" },
                { "sardinia" },
                { "sénégal", "senegal", "sn", "сенегал", "السنغال" },
                { "serbie", "serbia", "serbien", "srbija", "srbsko", "szerbia", "србија", "сърбия", "rs", "sérvia",
                        "serbija", "republika srpska", "republika srbska", "servië", "сербия", "塞尔维亚" },
                { "seychelles", "sc" },
                { "sierra leone", "sierra leona", "sl" },
                { "singapour", "singapore", "singapur", "singapura", "сингапур", "シンガポール", "sg", "ประเทศสิงคโปร์" },
                { "slovaquie", "slowakije", "sk", "slovakia", "slovačka", "slovensko", "slowakei", "slowakeije",
                        "szlovákia", "słowacja", "словакия", "slovacia", "sk:německo", "ประเทศสโลวาเกีย", "eslováquia",
                        "slovacchia" },
                { "slovénie", "slovenija", "slovenien", "slovinsko", "szlovénia", "słowenia", "словения", "si",
                        "slovenia", "slowenien", "eslovénia", "eslovenia", "словенија" },
                { "somalie", "somalía", "soomaaliya", "somalia", "galmudug", "so" },
                { "soudan", "sudan", "sudán", "sd", "السودان" },
                { "soudan du sud", "south sudan", "sudán del sur", "ss" },
                { "sri lanka", "ශ් රී ලංකාව", "lk" },
                { "suisse", "switzerland", "schweiz", "sveits", "sveitsi", "svezia", "svizzera", "svájc", "szwajcaria",
                        "švajčiarsko", "šveicarija", "švica", "švicarska", "švýcarsko", "ελβετία", "швейцария", "スイス",
                        "瑞士", "ch", "suiza", "suíça", "elveția", "fr:suisse", "ru:switzerland", "de:schweiz",
                        "fr:schweiz", "შვეიცარია", "ประเทศสวิตเซอร์แลนด์", "swiss", "zwitserland", "შვეიცარიา",
                        "швајцарска", "fr:ch" },
                { "suriname", "surinam", "суринам", "sr" },
                { "swaziland", "sz" },
                { "suède", "sweden", "rootsi", "ruotsi", "ruoŧŧa", "schweden", "sverige", "szwecja", "švedija",
                        "švedska", "švédsko", "швеция", "se", "sv", "zweden", "suecia", "suécia", "sv:sverige",
                        "sv:sweden", "nb:sverige", "zviedrija", "svezia", "السويد", "svédország", "nederländerna",
                        "швеція", "suedia" },
                { "syrie", "syria", "sy", "سوريا" },
                { "tadjikistan", "tadschikistan", "tajikistan", "таджикистан" },
                { "taïwan", "taiwan", "republika chińska", "republic of china", "tw", "台湾", "中華民國",
                        "república de china", "中華民国", "สาธารณรัฐจีน", "republik china" },
                { "tanzanie", "tanzania", "tz" },
                { "tchad", "chad", "td" },
                { "thaïlande", "thailand", "tailandia", "tailândia", "tajland", "tajlandia", "thaimaa", "thajsko",
                        "ประเทศไทย", "タイ王国", "泰国", "th", "ประเทศไทย (thai)", "ไทย", "hu:ประเทศไทย-thai",
                        "fr:ประเทศไทย (thai)", "thailandia" },
                { "timor oriental", "timor-leste" },
                { "togo", "tg" },
                { "tonga" },
                { "trinité-et-tobago", "trinidad y tobago", "trinidad and tobago", "tt" },
                { "tunisie", "tunisia", "tunesien", "tunezja", "tunis", "tunisien", "tunisko", "tunézia", "tunísia",
                        "تونس", "tn", "túnez", "ar:تونس", "тунис", "fr:tunisie" },
                { "turquie", "turkey", "birleşik krallik", "turchia", "turcia", "turcja", "turkije", "turkiye",
                        "turquia", "turquía", "turska", "tyrkia", "tyskland", "türkei", "türkiye", "турция", "تركيا",
                        "tr:turkey", "tr:türkiye", "ประเทศตุรกี", "de:türkei", "fr:turquie", "ro:turcia", "tr",
                        "tr:en:turkey" },
                { "turkménistan", "turkmenistan" },
                { "ukraine", "ucraina", "ucrania", "ucrânia", "ukraina", "ukrajina", "oekraïne", "україна", "украйна",
                        "ua", "украина" },
                { "uruguay", "uruguai", "uruguaia", "urugwaj", "uy", "es:uruguay" },
                { "vanuatu", "vu" },
                { "vatican", "vatican city", "va" },
                { "vénézuela", "venezuela", "ve" },
                { "vietnam", "viêt nam", "việt nam", "wietnam", "vn", "de:vietnam", "ประเทศเวียดนาม", "vietname" },
                { "wallis-et-futuna", "wallis and futuna", "wf" },
                { "yémen", "yemen", "اليمن", "ye", "عدن،صنعاء.", "صنعاء" },
                { "zambie", "zambia", "sambia", "zm" },
                { "zimbabwe", "zw" },
                { "monde", "world", "mondo", "mundo", "svijet", "svět", "мир", "свят", "世界", "worldwide", "welt",
                        "wereld", "โลก" },
                { "union européenne", "european union", "unione europea", "europese unie", "europäische union",
                        "evropska unija", "evropská unie", "eu", "unión europea", "ue", "ro:ue", "fr:union européenne",
                        "de:europäische union", "الاتحاد الأوروبي", "european union?", "união europeia",
                        "european-union", "ευρωπαϊκή ένωση", "uniunea europeană", "اوروبا" },
                { "afrique de l'ouest", "west africa" },
                { "asie du sud-est", "south-east asia", "south-east-asia" },
                { "inconnu", "inconnu/test", "exland", "testeste", "selestosina", "produtosil", "comidosil" }
        };

        processCountryMappings(rawMappings);
    }

    /**
     * Processes the provided raw country mappings, normalizes the data, and builds
     * a collection of
     * country definitions. Each country definition consists of a canonical name and
     * a set of unique
     * variants derived from the input.
     *
     * @param rawMappings an array of raw country mappings where each inner array
     *                    contains a canonical
     *                    name in the first element followed by its variants.
     *                    Variants are cleaned,
     *                    filtered, and normalized while duplicates are removed.
     */
    private static void processCountryMappings(String[][] rawMappings) {
        final int CANONICAL_NAME_INDEX = 0;
        final int FIRST_VARIANT_INDEX = CANONICAL_NAME_INDEX + 1;

        // Iterates raw mappings; builds normalized country definitions
        for (String[] mapping : rawMappings) {
            if (mapping == null || mapping.length == 0) {
                continue;
            }

            String canonicalName = mapping[CANONICAL_NAME_INDEX];
            String normalizedCanonicalName = cleanData(canonicalName).toLowerCase(Locale.ROOT);

            Set<String> uniqueVariants = Arrays.stream(mapping)
                    .skip(FIRST_VARIANT_INDEX) // Ignore the first element (canonical name)
                    .map(DataCountry::cleanData)
                    .filter(s -> !s.isEmpty())
                    .collect(Collectors.toCollection(LinkedHashSet::new));

            COUNTRY_DEFINITIONS.add(Country.builder()
                    .name(normalizedCanonicalName)
                    .variants(new ArrayList<>(uniqueVariants))
                    .build());
        }
    }

    private static String cleanData(String input) {
        if (input == null)
            return "";
        return input.trim().toLowerCase();
    }
}
